/**
 * Catálogo de objetos plausíveis para uma prefeitura mineira de porte médio.
 *
 * Cada entrada carrega o vocabulário que o fornecedor REALMENTE digita na
 * busca ("merenda", "asfalto", "remédio"), separado do nome oficial do objeto.
 * É esse par que faz a busca por "merenda" encontrar "gêneros alimentícios
 * para a alimentação escolar" — o teste explícito da definição de pronto.
 */
export const OBJETOS = [
  { chave: 'merenda', resumo: 'Registro de preços para aquisição de gêneros alimentícios para a alimentação escolar',
    secretaria: 'educacao', faixa: [380000, 1400000], modalidades: ['pregao_eletronico'], srp: true,
    sinonimos: ['merenda', 'merenda escolar', 'alimentação escolar', 'comida', 'alimento', 'cesta'],
    detalhe: 'Aquisição parcelada de gêneros alimentícios perecíveis e não perecíveis destinados ao preparo da alimentação escolar nas unidades da rede municipal de ensino, incluindo creches, pré-escolas e escolas de ensino fundamental, conforme quantitativos e especificações do Termo de Referência.' },
  { chave: 'medicamentos', resumo: 'Aquisição de medicamentos para a Farmácia Básica municipal',
    secretaria: 'saude', faixa: [220000, 900000], modalidades: ['pregao_eletronico'], srp: true,
    sinonimos: ['remédio', 'remedio', 'medicamento', 'farmácia', 'farmacia'],
    detalhe: 'Registro de preços para aquisição parcelada de medicamentos constantes da Relação Municipal de Medicamentos Essenciais, para atendimento das unidades básicas de saúde e da farmácia central.' },
  { chave: 'combustivel', resumo: 'Aquisição de combustíveis para a frota municipal',
    secretaria: 'administracao-e-financas', faixa: [600000, 2200000], modalidades: ['pregao_eletronico'], srp: true,
    sinonimos: ['combustível', 'combustivel', 'gasolina', 'diesel', 'etanol', 'posto', 'abastecimento'],
    detalhe: 'Aquisição parcelada de gasolina comum, óleo diesel S-10 e etanol para abastecimento da frota de veículos e máquinas do município, com fornecimento em posto situado no perímetro urbano.' },
  { chave: 'pavimentacao', resumo: 'Contratação de empresa para pavimentação asfáltica de vias urbanas',
    secretaria: 'obras-e-servicos-urbanos', faixa: [900000, 4000000], modalidades: ['concorrencia'], srp: false,
    sinonimos: ['asfalto', 'pavimentação', 'pavimentacao', 'recapeamento', 'obra', 'rua'],
    detalhe: 'Contratação de empresa de engenharia para execução de pavimentação asfáltica em concreto betuminoso usinado a quente, drenagem superficial, meio-fio e sinalização viária em vias do perímetro urbano, conforme projeto básico, memorial descritivo e planilha orçamentária.' },
  { chave: 'transporte-escolar', resumo: 'Contratação de transporte escolar para a zona rural',
    secretaria: 'educacao', faixa: [420000, 1600000], modalidades: ['pregao_eletronico'], srp: false,
    sinonimos: ['transporte escolar', 'ônibus', 'onibus', 'van', 'rota rural', 'perua'],
    detalhe: 'Contratação de empresa para prestação de serviço de transporte escolar de alunos da rede municipal e estadual residentes na zona rural, com veículos vistoriados e motoristas habilitados na forma da legislação de trânsito.' },
  { chave: 'residuos', resumo: 'Concessão dos serviços de coleta e destinação de resíduos sólidos urbanos',
    secretaria: 'meio-ambiente-e-agricultura', faixa: [1800000, 4000000], modalidades: ['concorrencia'], srp: false,
    sinonimos: ['lixo', 'resíduo', 'residuo', 'coleta', 'aterro', 'limpeza urbana'],
    detalhe: 'Contratação de empresa especializada na coleta regular de resíduos sólidos domiciliares, transporte e destinação final ambientalmente adequada em aterro sanitário licenciado, incluindo coleta seletiva no perímetro urbano.' },
  { chave: 'iluminacao', resumo: 'Manutenção preventiva e corretiva da iluminação pública',
    secretaria: 'obras-e-servicos-urbanos', faixa: [280000, 1100000], modalidades: ['pregao_eletronico'], srp: false,
    sinonimos: ['iluminação', 'iluminacao', 'poste', 'lâmpada', 'lampada', 'luz', 'led'],
    detalhe: 'Contratação de empresa para manutenção preventiva e corretiva do parque de iluminação pública, incluindo substituição de luminárias por tecnologia LED, com fornecimento de materiais e mão de obra.' },
  { chave: 'informatica', resumo: 'Aquisição de equipamentos de informática e infraestrutura de rede',
    secretaria: 'administracao-e-financas', faixa: [180000, 780000], modalidades: ['pregao_eletronico'], srp: false,
    sinonimos: ['computador', 'notebook', 'informática', 'informatica', 'rede', 'switch', 'servidor', 'ti'],
    detalhe: 'Aquisição de microcomputadores, notebooks, switches gerenciáveis, pontos de acesso sem fio e cabeamento estruturado para modernização da rede administrativa e das unidades de ensino.' },
  { chave: 'uniformes', resumo: 'Aquisição de uniformes e kits escolares para a rede municipal',
    secretaria: 'educacao', faixa: [140000, 620000], modalidades: ['pregao_eletronico'], srp: false,
    sinonimos: ['uniforme', 'camiseta', 'kit escolar', 'material escolar', 'mochila'],
    detalhe: 'Aquisição de uniformes escolares — camiseta, bermuda, agasalho e tênis — e kits de material escolar para os alunos matriculados na rede municipal de ensino.' },
  { chave: 'material-construcao', resumo: 'Registro de preços para aquisição de material de construção',
    secretaria: 'obras-e-servicos-urbanos', faixa: [200000, 850000], modalidades: ['pregao_eletronico'], srp: true,
    sinonimos: ['cimento', 'material de construção', 'construcao', 'tijolo', 'areia', 'brita'],
    detalhe: 'Registro de preços para aquisição parcelada de cimento, areia, brita, blocos, tubos, conexões e demais materiais destinados às obras e reparos executados por administração direta.' },
  { chave: 'odontologico', resumo: 'Aquisição de material odontológico para as unidades de saúde',
    secretaria: 'saude', faixa: [60000, 240000], modalidades: ['pregao_eletronico'], srp: true,
    sinonimos: ['odontológico', 'odontologico', 'dentista', 'dental', 'resina'],
    detalhe: 'Registro de preços para aquisição de material de consumo odontológico destinado aos consultórios das unidades básicas de saúde e ao serviço de odontologia móvel.' },
  { chave: 'patrulha', resumo: 'Aquisição de patrulha mecanizada agrícola',
    secretaria: 'meio-ambiente-e-agricultura', faixa: [420000, 1300000], modalidades: ['pregao_eletronico'], srp: false,
    sinonimos: ['trator', 'patrulha', 'agrícola', 'agricola', 'implemento', 'grade'],
    detalhe: 'Aquisição de trator agrícola, grade aradora, distribuidor de calcário e carreta basculante para composição de patrulha mecanizada destinada ao atendimento dos pequenos produtores rurais do município.' },
  { chave: 'locacao-veiculos', resumo: 'Locação de veículos para as secretarias municipais',
    secretaria: 'administracao-e-financas', faixa: [320000, 1200000], modalidades: ['pregao_eletronico'], srp: false,
    sinonimos: ['locação', 'locacao', 'aluguel de carro', 'veículo', 'veiculo', 'frota'],
    detalhe: 'Contratação de empresa para locação de veículos automotores sem motorista, com manutenção preventiva e corretiva inclusa, para uso das secretarias municipais.' },
  { chave: 'seguro-frota', resumo: 'Contratação de seguro para a frota de veículos do município',
    secretaria: 'administracao-e-financas', faixa: [45000, 180000], modalidades: ['pregao_eletronico'], srp: false,
    sinonimos: ['seguro', 'apólice', 'apolice', 'frota', 'sinistro'],
    detalhe: 'Contratação de seguro total para os veículos e máquinas que compõem a frota municipal, com cobertura compreensiva, assistência 24 horas e franquia reduzida.' },
  { chave: 'telefonia', resumo: 'Contratação de telefonia móvel e link dedicado de internet',
    secretaria: 'administracao-e-financas', faixa: [90000, 380000], modalidades: ['pregao_eletronico'], srp: false,
    sinonimos: ['internet', 'link', 'telefonia', 'celular', 'banda larga', 'fibra'],
    detalhe: 'Contratação de serviço de telefonia móvel com pacote de dados e de link dedicado de internet com garantia de banda para a sede administrativa e as unidades de saúde e ensino.' },
  { chave: 'leitos-saude', resumo: 'Credenciamento de prestadores de serviços de saúde e leitos hospitalares',
    secretaria: 'saude', faixa: [700000, 2600000], modalidades: ['credenciamento'], srp: false,
    sinonimos: ['leito', 'hospital', 'credenciamento', 'consulta', 'exame', 'saúde'],
    detalhe: 'Chamamento para credenciamento de pessoas jurídicas prestadoras de serviços de saúde interessadas em disponibilizar leitos hospitalares, consultas e exames especializados aos usuários do SUS residentes no município.' },
  { chave: 'festival', resumo: 'Contratação de atrações artísticas para o Festival de Inverno',
    secretaria: 'cultura-esporte-e-turismo', faixa: [120000, 460000], modalidades: ['inexigibilidade'], srp: false,
    sinonimos: ['show', 'banda', 'festival', 'música', 'musica', 'artista', 'inverno'],
    detalhe: 'Contratação de atrações artísticas para a programação do Festival de Inverno do município, por inexigibilidade de licitação, em razão da inviabilidade de competição decorrente da consagração da artista pela crítica especializada e pela opinião pública.' },
  { chave: 'bens-inserviveis', resumo: 'Alienação de bens móveis inservíveis do patrimônio municipal',
    secretaria: 'administracao-e-financas', faixa: [30000, 120000], modalidades: ['leilao'], srp: false,
    sinonimos: ['leilão', 'leilao', 'sucata', 'inservível', 'inservivel', 'veículo usado'],
    detalhe: 'Alienação, na modalidade leilão, de veículos, máquinas e equipamentos considerados inservíveis ou antieconômicos para a administração, avaliados por comissão designada e vendidos no estado de conservação em que se encontram.' },
  { chave: 'assistencia', resumo: 'Aquisição de cestas básicas para o programa de segurança alimentar',
    secretaria: 'assistencia-social', faixa: [90000, 340000], modalidades: ['pregao_eletronico'], srp: true,
    sinonimos: ['cesta básica', 'cesta', 'segurança alimentar', 'benefício eventual'],
    detalhe: 'Registro de preços para aquisição de cestas de alimentos destinadas à concessão de benefícios eventuais às famílias em situação de vulnerabilidade acompanhadas pelo CRAS.' },
  { chave: 'obras-creche', resumo: 'Construção de creche municipal em alvenaria estrutural',
    secretaria: 'obras-e-servicos-urbanos', faixa: [1200000, 3600000], modalidades: ['concorrencia'], srp: false,
    sinonimos: ['creche', 'construção', 'construcao', 'obra', 'escola', 'edificação'],
    detalhe: 'Contratação de empresa de engenharia para construção de unidade de educação infantil, incluindo fundação, estrutura, alvenaria, cobertura, instalações elétricas e hidrossanitárias, acabamentos e urbanização da área externa.' },
];

/** Razões sociais inventadas. NENHUMA empresa real — o briefing é explícito. */
export const FORNECEDORES = [
  'Serra Azul Comércio e Distribuição Ltda', 'Mantiqueira Suprimentos Corporativos EIRELI',
  'Alvorada Distribuidora de Alimentos Ltda', 'Construtora Pedra Branca Engenharia Ltda',
  'Vale Verde Serviços Urbanos S.A.', 'Cambuiense Transportes e Logística Ltda',
  'Boa Vista Comercial de Medicamentos Ltda', 'Nova Aurora Tecnologia da Informação Ltda',
  'Campo Belo Máquinas e Implementos Ltda', 'Primavera Confecções e Uniformes Ltda',
  'Sul Mineira Combustíveis e Derivados Ltda', 'Horizonte Locadora de Veículos EIRELI',
  'Braço das Antas Materiais de Construção Ltda', 'Clínica Integrada Bem Viver Ltda',
];

/** Nomes de arquivo propositalmente feios, para provar que o painel os
 *  transforma em título legível e que o layout aguenta o mundo real. */
export const NOMES_FEIOS = [
  'EDITAL_PE_032_2026_versao FINAL(2).pdf',
  'anexo I - termo de referencia_ATUALIZADO 11-02.pdf',
  'planilha_orcamentaria__CORRIGIDA.pdf',
  'ATA-DA-SESSAO-PUBLICA-assinada-digitalmente.pdf',
];
